name: ThinQ
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.0
  cloud_firestore: ^4.15.5
  cupertino_icons: ^1.0.8
  firebase_analytics: ^10.8.6
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.15
  firebase_database: ^10.4.6
  firebase_remote_config: ^4.3.14
  firebase_storage: ^11.6.6
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  gaimon: ^1.3.2
  google_generative_ai: ^0.4.7
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/items/
    - assets/images/characters/
    - assets/icon/
