// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
 
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
 
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA8OHzC0xvWxmLkiq54xVJTfddvhpWEpk',
    appId: '1:640777476330:web:655f7a1e304184f5355f93',
    messagingSenderId: '640777476330',
    projectId: 'lg-dx-school-5eaae',
    authDomain: 'lg-dx-school-5eaae.firebaseapp.com',
    databaseURL: 'https://lg-dx-school-5eaae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lg-dx-school-5eaae.firebasestorage.app',
    measurementId: 'G-Y0TSRLD0PQ',
  );
 
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe2SZbO06xL-UrZzku4G7XOjUrfscGeGo',
    appId: '1:640777476330:android:cdf8d6e667f05f60628a8e',
    messagingSenderId: '640777476330',
    projectId: 'lg-dx-school-5eaae',
    databaseURL: 'https://lg-dx-school-5eaae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lg-dx-school-5eaae.firebasestorage.app',
  );
 
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNWnXWUvRCKvtbLO7Um75_ZcCLJrHXKqk',
    appId: '1:640777476330:ios:e0be094b59c84273628a8e',
    messagingSenderId: '640777476330',
    projectId: 'lg-dx-school-5eaae',
    databaseURL: 'https://lg-dx-school-5eaae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lg-dx-school-5eaae.firebasestorage.app',
    iosBundleId: 'com.lgdxschool.ThinQ',
  );
}
 